# Linguagem Python em aprendizado de máquina

### Bruno Oliveira

## 1. Objetivos


Apresentar uma breve revisão da linguagem de programação Python, que é mais utilizada na área de aprendizado de máquina.

Introduzir conceito de tensores.

Apresentar a biblioteca de funções Numpy do Python.

Introdução à vetorização de cálculo.

Cálculo vetorizado usando Numpy.


## 2. Tensores


Tensor é um tipo de estrutura de dados que permite armazenar números em matrizes (“arrays”) de múltiplas dimensões.

Tensores são amplamente utilizados na área de aprendizado de máquina $\to$ é comum nas RNAs ter tensores de 5 ou mais eixos.

Importância dos tensores nas RNA é tão grande que um dos principais softwares da área é chamado TensorFlow.

Biblioteca de funções Numpy foi desenvolvida para trabalhar com tensores.

Existem inúmeras funções e métodos na biblioteca Numpy para operar com tensores.


#### Principais atributos de um tensor

Um tensor é definido por três atributos principais:

- Número de eixos (“rank”) $\to$ por exemplo, uma matriz possui 2 eixos, portanto, é um tensor 2D;


- Dimensão (“shape”) $\to$ descreve quantos elementos o tensor possui em cada eixo;


- Tipo de dados $\to$ descreve o tipo de dados que o tensor contém, por exemplo, inteiro (int8), (float32), string etc.


#### Principais tipos de tensores

Podemos definir tipos de sensores dependendo do número de eixos que possuem. Em relação a essa característica os principias tipos de tensores são:

- Escalar (0D);
- Vetor (1D);
- Matriz (2D);
- Tensores de 3 ou mais dimensões;

### 2.1 Escalar

Um tensor escalar possui dimensão zero (0D).

Tensor que armazena somente um número inteiro, real ou complexo.

Número de eixos de um tensor $\to$ obtido pelo método `ndim`.

Tipo de dados do tensor $\to$ obtido pelo método `dtype`.

Função `numpy.array` é usada para criar um tensor.

A célula abaixo apresenta um exemplo de um tensor escalar.

In [4]:
# Importa biblioteca numpy
import numpy as np

# Cria tensor escalar x 
x = np.array(12)

# Apresenta valor de x, número de eixos e tipo de dado
print('x =', x)
print('Número de eixos de x:', x.ndim)
print('Tipo de dado de x:', x.dtype)

x = 12
Número de eixos de x: 0
Tipo de dado de x: int32


- Antes de usar as funções da biblioteca Numpy deve-se importar a biblioteca para o programa. No código acima a biblioteca Numpy é importada com o nome `np` para facilitar escrever os comandos.


- Para criar um tensor usa-se a função Numpy `array`. 


### 2.2 Vetor

Vetor é um tensor de uma dimensão (1D), ou de um eixo.

Método `shape` fornece a dimensão de um tensor (número de linhas, número de colunas etc). 

Note que o número de eixos de um tensor também é chamado de “rank”. Cuidado para não confundir o número de eixos de um tensor com o número de elementos de um dos seus eixos.

Vetores são a forma mais comum de dados. Em um conjunto de dados, cada exemplo pode ser armazenado como um vetor coluna ou linha. Se colocarmos todos os exemplos juntos (colunas) temos uma matriz de dados, onde cada coluna representa um exemplo. 

A célula abaixo apresenta um exemplo de um tensor de 1D.

In [5]:
# Importa biblioteca numpy
import numpy as np

# Cria vetor x
x = np.array([12., 3., 6., -1.])

# Imprime vetor, número de eixos, dimensões dos eixos e tipo de dado
print('x =', x)
print('Número de eixos de x:', x.ndim)
print('Número de elementos em x:', x.shape)
print('Tipo de dados em x:', x.dtype)

x = [12.  3.  6. -1.]
Número de eixos de x: 1
Número de elementos em x: (4,)
Tipo de dados em x: float64


- Esse vetor tem 4 elementos. O método `shape` fornece o número de elementos de cada eixo do tensor, ou seja, a dimensão de cada eixo. 


- Novamente, cuidado para não confundir o número de elementos de cada eixo, obtido pelo método `shape`, com o número de eixos do tensor, obtido pelo método `ndim`.


- Os elementos desse vetor são números reais de 64 bits. O padrão em Python para representar números reais é 64 bits.


- O vetor é criado como sendo formado por números reais porque na sua criação os números foram definidos com o ponto decimal.


Existe uma diferença sutil entre tensores com dimensões `(n, )`, `(1, n)` e `(n, 1)`, onde `n` é o número de elementos do tensor. Todos esses três tensores tem um único eixo e, portanto, são vetores. 

- Um tensor de dimensão `(n, )` não é especificado se é um vetor linha ou coluna, somente que possui `n` elementos e ele pode ser usado como se fosse um vetor linha ou um vetor coluna. 
- Um tensor de dimensão `(n, 1)` é um tensor de `n` linhas e uma coluna, ou seja, é um vetor coluna.
- Um tensor de dimensão `(1, n)` é um tensor de uma linha e `n` colunas, ou seja, é um vetor linha. 

- Para indexar um elemento de um vetor de dimensão `(n, )`, deve-se usar em Numpy o comando `v[i]`, onde `v` é o vetor e `i` é o índice do elemento desejado. 

- Para indexar um elemento de um vetor de dimensão `(1, n)` ou `(n, 1)` deve-se usar `v[i][j]` ou `v[i,j]`, onde `v` é o vetor, `i` é o índice da linha e `j` é o índice da coluna. 

Na célula abaixo é mostrado um exemplo dessas três formas de definir um vetor e de como indexar seus elementos.

In [10]:
# Importa a biblioteca numpy
import numpy as np

# Cria vetor de 4 elementos
x = np.array([1.,2.,3.,4])

# Cria vetor linha de 4 elementos
xlinha = np.array([[1.,2.,3.,4]])

# Cria vetor coluna de 4 elementos
xcoluna = np.array([[1.],[2.],[3.],[4.]])

# Apresenta dimensões dos vetores
print('Dimensão do vetor x =', x.shape)
print('Dimensão do vetor xlinha =', xlinha.shape)
print('Dimensão do vetor xcoluna =', xcoluna.shape)

# Exemplo de como acessar os elementos desses vetores
print('Segundo elemento de x =', x[1])
print('Segundo elemento de xlinha =', xlinha[0,1])
print('Segundo elemento de xcoluna =', xcoluna[1],[0])

# Transforma vetor x de 4 elementos em um vetor coluna
xredim = np.reshape(x, (4,1))
print('Dimensão do vetor xredim =', xredim.shape)
print('xredim =',xredim)

Dimensão do vetor x = (4,)
Dimensão do vetor xlinha = (1, 4)
Dimensão do vetor xcoluna = (4, 1)
Segundo elemento de x = 2.0
Segundo elemento de xlinha = 2.0
Segundo elemento de xcoluna = 2.0
Dimensão do vetor xredim = (4, 1)
xredim = [[1.]
 [2.]
 [3.]
 [4.]]


- Observe que a indexação de tensores em Python começa com zero, ou seja, o primeiro elemento de um eixo é o elemento de índice 0.


- O método Numpy `reshape` serve para redimensionar dimensões de tensores, ou seja, para alterar os números de elementos dos seus eixos. Esse método não altera o número total de elementos do tensor, somente rearranja os seus elementos.


### 2.3 Matrizes

Matriz é um  tensor de duas dimensões (2D), ou de dois eixos:
	
- Primeiro eixo $\to$ `eixo[0]` representa as linhas;
- Segundo eixo $\to$ `eixo[1]` representa as colunas.

Uma matriz pode ser considerada como sendo um “array” de vetores. 

Um exemplo típico de dados de 2D é uma imagem em tons de cinza, onde o primeiro eixo representa a altura da imagem e o segundo eixo a largura. Cada elemento da matriz consiste de um número que representa a intensidade luminosa daquele local da imagem.

Por exemplo, um conjunto de 128 imagens em tons de cinza, cada uma com dimensão 32x32 pode ser armazenado em um tensor de 3 eixos de dimensão `(128, 32, 32)` ou `(32, 32, 128)`.

A célula abaixo apresenta exemplo de um tensor de 2D.

In [11]:
# Importa a biblioteca numpy
import numpy as np

# Cria matriz A
A = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]], dtype='float32')

# Apresenta matriz, número de eixos, dimensões dos eixos, tipo de dados, 
# número de linhas e colunas, e elemento de índice (3,1)
print('Matriz A =', A)
print('Número de eixos =', A.ndim)
print('Número de elementos em cada eixo =', A.shape)
print('Tipo de elemento =', A.dtype)
print('Número de linhas =', A.shape[0])
print('Número de colunas =', A.shape[1])
print('Elemento (3,1) =', A[2,0])

Matriz A = [[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]]
Número de eixos = 2
Número de elementos em cada eixo = (4, 3)
Tipo de elemento = float32
Número de linhas = 4
Número de colunas = 3
Elemento (3,1) = 3.0


### 2.4 Tensores 3D ou de mais eixos

Tensor de 3 dimensões (3D) é um tensor de três eixos:

- Primeiro eixo $\to$ `eixo[0]` representa as linhas;
- Segundo eixo $\to$ `eixo[1]` representa as colunas;
- Terceiro eixo $\to$ `eixo[2]` representa a profundidade.

Se juntarmos várias matrizes em um único tensor teremos um tensor de 3 eixos (3D), que pode ser visualizado como um cubo ou um paralelepípedo.

Um tensor 3D pode ser considerado como sendo um `array` de matrizes.

Se juntarmos vários tensores 3D em um único tensor teremos um tensor 4D e, assim, por diante.

Um exemplo típico de dados 3D é uma imagem colorida, onde o primeiro eixo representa a altura, o segundo eixo a largura e o terceiro eixo a cor.

Por exemplo, um conjunto de 128 imagens coloridas, cada uma com dimensão `(32, 32, 3)` pode ser armazenado em um tensor de 4 eixos de dimensão `(32, 32, 3, 128)` ou `(128, 32, 32, 3)`.

Um exemplo típico de dados 4D é um vídeo que consiste de um `array` de imagens, sendo que cada imagem do vídeo possui 3 eixos. O quarto eixo de um vídeo representa o tempo.

Por exemplo, um vídeo de 60 segundos, amostrado com 10 quadros por segundo, se cada quadro do vídeo é uma imagem colorida de dimensão `(256, 256, 3)`, então, esse vídeo pode ser armazenado em um tensor de 4 eixos de dimensão `(256, 256, 3, 600)`.

O código da célula abaixo apresenta exemplo de um tensor de 3D.

In [12]:
# Importa a biblioteca numpy
import numpy as np

# Cria tensor T
T = np.array([[[1,-1],[2,-2],[3,-3]],[[2,-2],[3,-3],[4,-4]],[[3, -3],[4, -4],[5,-5]], [[4, -4],[5, -5],[6,-6]]])

# Apresenta tensor, número de eixos, dimensões dos eixos e tipo de dados
print('T =', T)
print('Número de eixos =', T.ndim)
print('Número de elementos em cada eixo =', T.shape)
print('Tipo de elemento =', T.dtype)

# Elemento (3, 1, 2) do tensor T
print('Elemento de índice (3,1,2) =', T[2,0,1])

T = [[[ 1 -1]
  [ 2 -2]
  [ 3 -3]]

 [[ 2 -2]
  [ 3 -3]
  [ 4 -4]]

 [[ 3 -3]
  [ 4 -4]
  [ 5 -5]]

 [[ 4 -4]
  [ 5 -5]
  [ 6 -6]]]
Número de eixos = 3
Número de elementos em cada eixo = (4, 3, 2)
Tipo de elemento = int32
Elemento de índice (3,1,2) = -3


- O tensor `T` acima tem dimensão `(4, 3, 2)` e pode ser visto como sendo formado por 4 matrizes de 3 linhas e 2 colunas cada, ou também pode ser visto como sendo formado por duas matrizes de 4 linhas e 3 colunas cada.

## 3. Seleção de elementos de um tensor


Em muitas situações é necessário realizar operações com somente parte de um tensor.

É possível selecionar somente alguns elementos de um tensor numpy.

Seja um tensor de dimensão `(100, 32, 64)`, que pode ser, por exemplo, 100 imagens em tons de cinza, cada uma com tamanho de 32 por 64 pixels. 

O código da ceélula abaixo 5 mostra alguns exemplos de como selecionar elementos desse tensor.

In [13]:
# Importa bilblioteca numpy
import numpy as np

# Cria tensor de 100 imagens com números aleatórios
imagens = np.random.randint(256, size=(100, 32, 64))

# Apresenta dimensões do tensor com as imagens
print('Dimensões dos eixos do tensor =', imagens.shape)

# Seleciona as imagens de números 10 a 99
imagens1 = imagens[10:100,:,:]
print('Dimensão dos eixos do novo tensor =', imagens1.shape)

# Seleciona parte das imagens com as 16 primeiras linhas e colunas
imagens2 = imagens[:,:16,:16]
print('Dimensão dos eixos do novo tensor =', imagens2.shape)

# Seleciona a parte central das imagens com tamanho de 16 linhas por
# 24 colunas 
imagens3 = imagens[:,8:-8,20:-20]
print('Dimensão dos eixos do novo tensor =', imagens3.shape)

# Seleciona parte das imagens com as 10 últimas colunas e 12 últimas
# linhas
imagens4 = imagens[:,-10:,-12:]
print('Dimensão dos eixos do novo tensor =', imagens4.shape)

Dimensões dos eixos do tensor = (100, 32, 64)
Dimensão dos eixos do novo tensor = (90, 32, 64)
Dimensão dos eixos do novo tensor = (100, 16, 16)
Dimensão dos eixos do novo tensor = (100, 16, 24)
Dimensão dos eixos do novo tensor = (100, 10, 12)


- Função  `np.random.randint()` serve para criar um tensor com números inteiros aleatórios. O primeiro argumento dessa função é o valor máximo desejado para os números e o segundo argumento é a dimensão desejada para cada eixo do tensor, que no caso é um tensor 3D de dimensão (100, 32, 64).


- Usar dois pontos em um eixo representa selecionar todos os elementos dessa dimensão.


- Selecionar as imagens usando `10:100` no primeiro eixo, significa escolher as imagens de índices 10 a 99. A imagem de índice 10 é incluída, mas a de índice 100 fica fora.


- Selecionar os elementos de um eixo usando `:16`, significa escolher do primeiro elemento, de índice 0, até o décimo sexto elemento de índice 15.


- Selecionar elementos de índice `8:-8`, significa escolher os elementos começando do elemento de índice 8 até o elemento correspondente ao de índice final menos 8.


- Selecionar elementos de um eixo usando `-10:`, representa selecionar os 10 últimos elementos.


## 4. Operações com tensores

Todas as operações em uma RNA podem ser reduzidas para um pequeno conjunto de operações usando tensores.

É possível realizar operações com tensores, tais como, adicionar, multiplicar, dividir e outras operações mais complexas sem a necessidade de usar comandos de repetição para lidar com cada elemento dos tensores isoladamente $\to$ essa forma eficiente de operar com tensores é chamada de cálculo vetorizado.

O que é vetorização de cálculo?
 
- Uma forma de realizar cálculos numéricos com computador evitando ao máximo comandos de repetição explícitos, como por exemplo, “for-loops”.

- Os cálculos são realizados diretamente com tensores usando funções desenvolvidas especialmente para isso.


Em Python cálculo vetorizado de tensores é realizado pelas funções da biblioteca Numpy.

A biblioteca Numpy possui diversas funções matemáticas que realizam cálculos diretamente em tensores.

Deve-se ter cuidado porque algumas funções da biblioteca Numpy realizam os cálculos elemento por elemento e outras realizam o cálculo considerando as regras da álgebra linear para multiplicar matrizes e vetores.

Outra biblioteca de funções Python que implementa cálculo vetorizado é o TensorFlow, que é uma das ferramentas mais usadas para desenvolver sistemas de inteligência artificial com redes neurais deep-learning.

Cálculo vetorizado é muito mais rápido do que não vetorizado e é facilmente implementado usando múltiplas CPUs e em GPU (Graphics Processing Unit – Placa de Vídeo).

Existem quatro tipos de operações básicas com tensores:

1. Operação elemento por elemento (“element-wise”);
2. Produto de tensores (“dot-product”);
3. Redimensionamento de tensores (“reshaping”);
4. Ajuste de dimensões (“Broadcasting”).


### 4.1 Operação elemento por elemento (“element-wise”)

Operações elemento por elemento de tensores são operações aplicadas independentemente em cada elemento do tensor.

Duas funções convenientes da biblioteca Numpy para criar tensores com todos elementos iguais a zero e um, são:

- Tensor de zeros $\to$  `u = zeros((n,m))`, onde `(n, m)` é uma tuple, sendo que n = número de linhas e m = número de colunas;

- Tensor de uns $\to$ `v = ones((n, m))`.

O código da célula abaixo 6 apresenta uma implementação ingênua para calcular a soma e o produto de dois vetores elemento por elemento.

In [15]:
# Importa bilblioteca numpy
import numpy as np

# Cria e inicializa os vetores
x = np.array([1.,2.,3.,4.,5.]) # cria vetor x 1D
y = np.array([-1,-2,-3,-4,-5]) # cria vetor y 1D
z = np.zeros(x.shape) # inicializa vetor 1D para armazenar soma x + y
w = np.zeros(x.shape) # inicializa vetor 1D para armazenar produto x*y

# Salva número de elementos dos vetores
n = x.shape[0] 

# Comando de repetição para calcular cada elemento dos vetores z e w
for i in range(n):
    z[i] = x[i] + y[i]
    w[i] = x[i]*y[i]
    
# Apresenta resultados
print('Vetor x =', x)
print('Vetor y =', y)
print('Soma dos elementos de x e y =', z)
print('Produto dos elementos de x e y =', w)

Vetor x = [1. 2. 3. 4. 5.]
Vetor y = [-1 -2 -3 -4 -5]
Soma dos elementos de x e y = [0. 0. 0. 0. 0.]
Produto dos elementos de x e y = [ -1.  -4.  -9. -16. -25.]


- Observa-se que ao criar os vetores `z` e `w` com zeros, as suas dimensões são definidas como sendo iguais a do vetor `x` usando o método `x.shape`.

O código do abaixo apresenta os mesmos cálculos realizados na célula anterior, mas usando funções da biblioteca Numpy com tensores $\to$ além de ser muito mais fácil é muito mais rápido computacionalmente.

In [16]:
# Operação vetorizada de soma de dois vetores elemento-por-elemento
z = x + y

# Operação vetorizada do produto de dois vetores elemento-por-
# elemento
w = x*y

# Apresenta resultados
print('Soma dos elementos de x e y =', z)
print('Produto dos elementos de x e y =', w)

Soma dos elementos de x e y = [0. 0. 0. 0. 0.]
Produto dos elementos de x e y = [ -1.  -4.  -9. -16. -25.]


### 4.2 Ajuste automático de dimensões de tensores (“broadcasting”)


Ao somar e multiplicar tensores elemento por elemento o número de eixos e as dimensões de cada eixo devem ser iguais nos dois tensores.

Quando não existe nenhuma ambigüidade em uma operação elemento por elemento de dois tensores as funções da biblioteca Numpy ajustam as dimensões dos tensores automaticamente.

Exemplos de ajuste automático de dimensões:

1. No caso de soma, subtração, multiplicação ou divisão de um tensor com um escalar, todos os elementos do tensor são somados, subtraídos, multiplicados ou divididos pelo número. Por exemplo:

$$\begin{pmatrix}1\\2\\3\\4\end{pmatrix} + 100 = \begin{pmatrix}101\\102\\103\\104\end{pmatrix}$$  
   
$$\begin{pmatrix}1 & 2 & 3\end{pmatrix} + 100 = \begin{pmatrix}101 & 102 & 103\end{pmatrix}$$
 
2. No caso de soma, subtração, multiplicação ou divisão de um tensor de mais de um eixo com um vetor, o vetor deve ter o mesmo número de elementos de um dos eixos do tensor e nessa operação todos os elementos do tensor ao longo desse eixo são somados, subtraídos, multiplicados ou divididos pelo respectivo elemento do vetor. Por exemplo:

$$\begin{pmatrix}1 & 2 & 3 \\4 & 5 & 6\\\end{pmatrix} + \begin{pmatrix}100 & 200 & 300\end{pmatrix} = \begin{pmatrix}101 & 202 & 303 \\104 & 205 & 306\end{pmatrix}$$

$$\begin{pmatrix}1 & 2 & 3 \\4 & 5 & 6\\\end{pmatrix} + \begin{pmatrix}100\\200\end{pmatrix} = \begin{pmatrix}101 & 102 & 103 \\204 & 205 & 206\end{pmatrix}$$


#### Regras gerais

As regras gerais de ajuste automático de dimensões de tensores em operações realizadas elemento por elemento são as seguintes:

1. Vetor (m, 1)  $+/-/*/\div$ escalar  = vetor (m, 1)


2. Vetor (1, n)  $+/-/*/\div$ escalar  = vetor (1, n)


3. Matriz (m, n)  $+/-/*/\div$ vetor (1, n) = matriz (m, n)


4. Matriz (m, n)  $+/-/*/\div$ vetor (m, 1) = matriz (m, n)


5. No caso de um tensor de 4 eixos com dimensão (m1, m2, m3, n)  $+/-/*/\div$ vetor (1, n) = tensor (m1, m2, m3, n);


6. No caso de um tensor de 4 eixos com dimensão (m1, m2, m3, n) $+/-/*/\div$ vetor (m3, 1) = tensor (m1, m2, m3, n)


Os símbolos $+/-/*/\div$ nas regras anteriores significam que elas valem para as operações de soma, subtração, multiplicação e divisão. Essas regras valem para tensores de qualquer número de eixos e pode-se realizar operações de tensores de múltiplos eixos com outros tensores também de múltiplos eixos, desde que as dimensões dos respectivos eixos sejam iguais. 


No código são apresentados alguns exemplos de utilização das regras de ajuste automático de dimensões.

In [17]:
# Importa bilblioteca numpy
import numpy as np

# Cria tensores A e x
A = np.array([[[1,1],[2,2],[3,3]],[[2,2],[3,3],[4,4]],[[3, 3],[4, 4],[5,5]], [[4, 4],[5, 5],[6,6]]])
x = np.array([[100], [200], [300]])

# Soma tensor A com vetor x
B = A + x

# Apresenta tensores A, x e B = A + x
print('A =', A)
print('Dimensão de A =', A.shape, '\n')
print('x =', x)
print('Dimensão de x =', x.shape,'\n')
print('B = A + x =', B)
print('Dimensão de B =', B.shape, '\n')

A = [[[1 1]
  [2 2]
  [3 3]]

 [[2 2]
  [3 3]
  [4 4]]

 [[3 3]
  [4 4]
  [5 5]]

 [[4 4]
  [5 5]
  [6 6]]]
Dimensão de A = (4, 3, 2) 

x = [[100]
 [200]
 [300]]
Dimensão de x = (3, 1) 

B = A + x = [[[101 101]
  [202 202]
  [303 303]]

 [[102 102]
  [203 203]
  [304 304]]

 [[103 103]
  [204 204]
  [305 305]]

 [[104 104]
  [205 205]
  [306 306]]]
Dimensão de B = (4, 3, 2) 



In [18]:
# Importa bilblioteca numpy
import numpy as np

# Cria tensores A e Y
A = np.array([[[1,1],[2,2],[3,3]],[[2,2],[3,3],[4,4]],[[3, 3],[4, 4],[5,5]], [[4, 4],[5, 5],[6,6]]])
Y = np.array([[100, 200], [100,200], [100,200]])

# Soma tensor A com matriz Y
C = A + Y  

# Apresenta tensores A, Y e C = A + Y
print('A =', A)
print('Dimensão de A =', A.shape, '\n')
print('Y =', Y)
print('Dimensão de Y =', Y.shape, '\n')
print('C = A + Y =', C)
print('Dimensão de C =', C.shape, '\n')

A = [[[1 1]
  [2 2]
  [3 3]]

 [[2 2]
  [3 3]
  [4 4]]

 [[3 3]
  [4 4]
  [5 5]]

 [[4 4]
  [5 5]
  [6 6]]]
Dimensão de A = (4, 3, 2) 

Y = [[100 200]
 [100 200]
 [100 200]]
Dimensão de Y = (3, 2) 

C = A + Y = [[[101 201]
  [102 202]
  [103 203]]

 [[102 202]
  [103 203]
  [104 204]]

 [[103 203]
  [104 204]
  [105 205]]

 [[104 204]
  [105 205]
  [106 206]]]
Dimensão de C = (4, 3, 2) 



### 4.3 Produto de dois tensores (“dot-product”)

O produto de dois tensores é a operação mais comum e talvez a mais útil nos cálculos realizados nas RNAs.

Essa operação é chamada de "dot-product” a partir de uma analogia com o produto escalar de dois vetores.

Essa operação é implementada pela função Numpy `dot`, cujo nome é dado a partir da analogia com o nome em inglês usado para designar o produto escalar de dois vetores (“dot product”).

A regra utilizada segue os princípios da álgebra linear e as dimensões dos tensores devem ser compatíveis para poder realizar o produto dos mesmos. Por exemplo:

- A operação “dot-product” é igual ao produto escalar de dois vetores para o caso dos tensores serem 1D, ou seja, vetores.

- A operação “dot-product” é igual ao produto de uma matriz por um vetor quando um dos tensores é 2D e o outro é 1D com as dimensões corretas para poder realizar a operação.

- Somente é possível realizar o produto de duas matrizes `A` e `B`, se a dimensão do segundo eixo de `A` for igual à dimensão do primeiro eixo de `B`, ou seja, `dot(A, B)` somente é possível se `A.shape[1] = B.shape[0]` e o resultado é uma matriz de dimensões `A.shape[0] por B.shape[1]`.

As regras gerais para a compatibilidade das dimensões dos dois tensores são as seguintes:

`(a, ) x (a, )` $\to$ `(1)`

`(1, a) x (a, 1)` $\to$ `(1)`

`(a, 1) x (1, b)`  $\to$ `(a, b)`

`(a, b) x (b, )` $\to$ `(a, )`

`(a, b, c) x (c, )` $\to$ `(a, b)`

`(a, b, c, d) x (d, )` $\to$ `(a, b, c)`

`(a, b, c, d) x (d, e)` $\to$ `(a, b, c, e)`

onde `1`, `a`, `b`, `c`, `d` e `e` são as dimensões dos eixos dos tensores.

Note que o produto de dois tensores não tem propriedade comutativa, ou seja, segue os mesmos conceitos da álgebra linear para produto de duas matrizes, assim:

`dot(A, B)` $\neq$ `dot(B, A)`

O código abaixo apresenta uma implementação ingênua para calcular o produto escalar de dois vetores com mesmas dimensões e o produto de uma matriz por um vetor.

In [25]:
# Importa bilblioteca numpy
import numpy as np

# Cria vetores e matrizes
x = np.ones((3,))
y = np.array([1., 2., 3.])
A = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]], dtype='float32')
w = np.zeros(A.shape[0])

# Recupera dimensões dos tensores
m, n = A.shape

# Comando de repetição para calcular o produto dos vetores x e y
z = 0
for i in range(n):
    z = z + x[i]*y[i]
    
# Comandos de repetição para calcular o produto da matriz A pelo
# vetor y
for i in range(m):
    for j in range(n):
        w[i] = w[i] + A[i][j]*y[j]

# Apresentação dos resultados
print('Dimensão de x =', x.shape)
print('Dimensão de y =', y.shape)
print('Dimensão de A =', A.shape)
print('Dimensão de w =', w.shape)
print("x = ",x)
print("y = ",y)
print("A = ",A)
print("z = ",z)
print("w = ",w)

Dimensão de x = (3,)
Dimensão de y = (3,)
Dimensão de A = (4, 3)
Dimensão de w = (4,)
x =  [1. 1. 1.]
y =  [1. 2. 3.]
A =  [[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]
z =  6.0
w =  [ 6. 12. 18. 24.]


- O comando `x += y`, representa uma notação mais curta para a operação `x = x + y`.

O código a seguir apresenta os mesmos cálculos realizados na célula enterior, porém de forma vetorizada.

In [23]:
# Cálculo vetorizado do produto dos vetores x e y
z = np.dot(x,y)

# Cálculo vetorizado do produto da matriz A pelo vetor y
w = np.dot(A,y)

# Apresentação dos resultados
print("x = ",x)
print("y = ",y)
print("A = ",A)
print("z = ",z)
print("w = ",w)

x =  [1. 1. 1.]
y =  [1. 2. 3.]
A =  [[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]
z =  6.0
w =  [ 6. 12. 18. 24.]


- O produto de dois vetores de dimensão `(n, )` é um escalar independentemente do número de elementos dos vetores e não importa a ordem em que são multiplicados.


- Se os vetores `x` e `y` tivessem ambos as mesmas dimensões, seja (3, 1) ou (1, 3), a utilização da função `dot(x, y)` para multiplicá-los geraria um erro, pois não obedeceria as regras da álgebra linear.


- Se o vetor `x` tivesse dimensão (3, 1) e o vetor y dimensão (1, 3) o resultado da operação `dot(x, y)` seria uma matriz de dimensão (3,3).


- A multiplicação de uma matriz de dimensão (4, 3) por um vetor de dimensão (3, ) é um vetor de dimensão (4, )


- Como a matriz `A` tem dimensão (3, 3), então, se o vetor y tivesse dimensão (3, 1), a função `dot(A, y)` funcionaria da mesma forma


- Se o vetor `y` tivesse dimensão (1, 3), a função `dot(A, y)` geraria erro, pois não obedeceria as regras da álgebra linear.


### 4.4	Redimensionamento de tensores (“reshaping”)

Uma operação essencial de tensores, que é muito usada nas redes neurais, é o seu redimensionamento. 

Redimensionar um tensor significa rearranjar suas linhas e colunas para se obter um novo tensor com novos eixos de dimensões diferentes. Obviamente que o tensor redimensionado tem os mesmos elementos que o tensor original.

Um caso especial de redimensionamento de tensores é a sua transposição. Transpor uma matriz significa trocar suas linhas por suas colunas. 

No código abaixo são apresentados alguns exemplos de redimensionamento de tensores usando as funções `reshape` e `transpose` da biblioteca Numpy.


In [24]:
# Importa bilblioteca numpy
import numpy as np

# Cria tensor X 2D
X = np.array([[0., 1.],[2., 3.],[4., 5.]])
print("X = ",X)
print("Dimensão de X =", X.shape, '\n')

# Cria vetor y redimensionando tensor X (seguindo as suas linhas)
y = X.reshape((6,1)) #np.reshape(X, (6,1))
print("y = ", y)
print("Dimensão de y =", y.shape,'\n')

# Cria vetor z redimensionando tensor X (seguindo as suas colunas)
z = X.reshape((6,1), order='F')
print("z = ", z)
print("Dimensão de z =", z.shape,'\n')

# Cria tensor W pelo redimensionando tensor X
W = X.reshape((2,3))
print("W = ", W)
print("Dimensão de W =", W.shape,'\n')

# Transpõe tensor W
W = np.transpose(W) #W.T
print("W transposto = ", W)
print("Dimensão de w transposto =", W.shape)

X =  [[0. 1.]
 [2. 3.]
 [4. 5.]]
Dimensão de X = (3, 2) 

y =  [[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]
Dimensão de y = (6, 1) 

z =  [[0.]
 [2.]
 [4.]
 [1.]
 [3.]
 [5.]]
Dimensão de z = (6, 1) 

W =  [[0. 1. 2.]
 [3. 4. 5.]]
Dimensão de W = (2, 3) 

W transposto =  [[0. 3.]
 [1. 4.]
 [2. 5.]]
Dimensão de w transposto = (3, 2)


- O padrão da função reshape é alocar os elementos no novo tensor seguindo as linhas do tensor original. Contudo, isso pode ser alterado de forma a seguir os elementos pelas colunas usando a opção order. 


- O cálculo da transposta da matriz `W` poderia ser realizado alternativamente simplesmente por `W.T`, onde o `T` representa transposta.


## 5. Funções comuns da biblioteca Numpy 

Existem muitas funções que implementam operações elemento por elemento na biblioteca Numpy. Exemplos de algumas dessas funções são exponencial, logaritmo e potência, cuja utilização é apresentada na célula abaixo.

In [27]:
# Importa bilblioteca numpy
import numpy as np

# Cria vetor x
x = np.array([1, -10, 100])

# Calcula e apresenta exponencial, logaritmo base 10, logaritmo 
# neperiano, valor absoluto e quadrado dos elementos do tensor
print('Exponencial de x =', np.exp(x))
print('Log10 de x =', np.log10(x))
print('Ln(x) =', np.log(x))
print('Valor absoluto de x =', np.abs(x))  
print('Quadrado de x = ', np.power(x,2))

Exponencial de x = [2.71828183e+00 4.53999298e-05 2.68811714e+43]
Log10 de x = [ 0. nan  2.]
Ln(x) = [0.                nan 4.60517019]
Valor absoluto de x = [  1  10 100]
Quadrado de x =  [    1   100 10000]


C:\Users\jklca\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in log10
  # Remove the CWD from sys.path while we load stuff.
C:\Users\jklca\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in log
  # This is added back by InteractiveShellApp.init_path()


- Note que o segundo elemento do vetor `x` é negativo, portanto, o seu logaritmo não existe e assim o resultado desse cálculo aparece como sendo `nan`, que em Python significa que não existe.

Outras quatro funções muito utilizadas são:

- `max`: calcula o valor máximo dos elementos de um tensor;
- `min`: calcula o valor mínimo dos elementos de um tensor;
- `mean`: calcula a média dos elementos de um tensor;
- `std`: calcula o desvio padrão dos elementos de um tensor.

Se o tensor tiver mais do que um eixo é necessário indicar o eixo ao longo do qual se deseja realizar a operação utilizando o argumento `axis` $\to$ se não for indicado nenhum eixo, então, o padrão da função é utilizado operando em todos os elementos do tensor.


No código abaixo são apresentados exemplos de uso dessas funções.

In [29]:
# Importa bilblioteca numpy
import numpy as np

# Define matriz A
A = np.array([[1., 2., 3.], [4., 5., 6.]])

# Calcula e apresenta max, min, média e desvio padrão
print(' A = ', A)
print('Valor máximo de A =', np.max(A))
print('Valor máximo de cada coluna de A =', np.max(A, axis=0))
print('Valor máximo de cada linha de A =', np.max(A, axis=1))
print('Valor mínimo de A =', np.min(A))
print('Valor mínimo de cada coluna de A =', np.min(A, axis=0))
print('Valor mínimo de cada linha de A =', np.min(A, axis=1))
print('Valor médio de A =', np.mean(A))
print('Valor médio de cada coluna de A =', np.mean(A, axis=0))
print('Valor médio de cada linha de A =', np.mean(A, axis=1))
print('Desvio padrão de A =', np.std(A))
print('Desvio padrão de cada coluna de A =', np.std(A, axis=0))
print('Desvio padrão de cada linha de A =', np.std(A, axis=1))

 A =  [[1. 2. 3.]
 [4. 5. 6.]]
Valor máximo de A = 6.0
Valor máximo de cada coluna de A = [4. 5. 6.]
Valor máximo de cada linha de A = [3. 6.]
Valor mínimo de A = 1.0
Valor mínimo de cada coluna de A = [1. 2. 3.]
Valor mínimo de cada linha de A = [1. 4.]
Valor médio de A = 3.5
Valor médio de cada coluna de A = [2.5 3.5 4.5]
Valor médio de cada linha de A = [2. 5.]
Desvio padrão de A = 1.707825127659933
Desvio padrão de cada coluna de A = [1.5 1.5 1.5]
Desvio padrão de cada linha de A = [0.81649658 0.81649658]


## 6. Funções customizadas

Como em qualquer linguagem de programação é possível criar novas funções utilizando as funções da biblioteca Numpy e obviamente elas serão capazes de realizar cálculos de forma vetorizada. 


#### Exemplo1: Normalização de dados

Uma operação comum em aprendizado de máquina é normalizar os dados. Seja um conjunto de dados composto por $m$ vetores, cada um com $n$ elementos. Esses dados são colocados em uma matriz $V$ com $m$ linhas e $n$ colunas:


$$V = \begin{pmatrix}v_1\\ \vdots \\v_m\end{pmatrix}_{(m,n)}$$   	

onde $v_i$ é a $i$-ésima linha da matriz $V$, ou seja, é um vetor linha de $n$ elementos.

Uma forma de normalizar dados é ter o módulo (ou norma) de cada dado igual a um. O módulo de um vetor $v$ é igual ao seu comprimento, sendo calculado por:

$$||v||_2 = \sqrt{v_1^2 + v_2^2 +...+ v_n^2}$$


onde $||v||_2$ é o módulo do vetor $v$, $n$ é o número de elementos do vetor e $v_i$ é o $i$-ésimo elemento do vetor. A normalização das linhas da matriz $V$ é feita dividindo cada elemento de cada linha pelo módulo da linha, que pode ser realizada por uma operação vetorizada da seguinte forma:

$$v_{i,norm} = \frac{v_i}{||v_i||_2}$$

Dessa forma a matriz $V$ com as suas linhas normalizadas ($V_{norm}$) é dada por:

$$V = \begin{pmatrix}\frac{v_1}{||v_1||_2}\\ \vdots \\ \frac{v_m}{||v_m||_2}\end{pmatrix}_{(m,n)}$$

No código abaixo é criada e executada uma função que normaliza as linhas de uma matriz, ou seja, todas as linhas da matriz resultante têm módulo igual a um.

In [33]:
# Função com cálculo vetorizado para normalizar linhas de uma matriz
def norm2(V):
    """
    Argumento: V = matriz numpy de dimensões (m, n)
    Retorna:
    Vnorm = matriz normalizada linha por linha
    lin_norm = norma das linhas da matriz original
    """
    
    # Cálculo da norma de cada linha da matriz V
    lin_norm = np.linalg.norm(V, ord=2, axis = 1, keepdims = True)
    
    # Normalização das linhas na matriz
    Vnorm = V/lin_norm

    return Vnorm, lin_norm

# Define uma matriz e executa função norm_lin
V = np.array([[1, 2, 3], [2, 3, 4]])
Vnorm, lin_norm = norm2(V)

print('Matriz V =', V)
print('Normas das linhas da matriz =', lin_norm)
print('Matriz com linhas normalizadas =', Vnorm)

Matriz V = [[1 2 3]
 [2 3 4]]
Normas das linhas da matriz = [[3.74165739]
 [5.38516481]]
Matriz com linhas normalizadas = [[0.26726124 0.53452248 0.80178373]
 [0.37139068 0.55708601 0.74278135]]


- Nota-se que as normas das linhas da matriz são retornadas pela função `norm_lin()` somente para poderem ser visualizadas.

- A função `linalg.norm()` calcula norma de tensores e pertence à classe `linalg` da biblioteca Numpy.

- A função `linalg.norm()` possui alguns argumentos para definir o cálculo desejado:

    - O tipo de norma que se deseja calcular é definido pelo argumento `ord`, que no caso da norma calculada no código acima  é a Forbenuis, ou norma-2. 
    
    - O eixo que se deseja calcular a norma é definido por `axis`, no caso como se deseja calcular a norma da cada linha é definido `axis=0`.
    
    - Se for desejado calcular a norma de cada coluna deve-se usar `axis=1`.
    
    - Finalmente o argumento `keepdims=True`, mantém a dimensão do tensor a menos do eixo que é calculada a norma.

#### Exemplo 2: Normalização de dados

Outra forma de normalizar dados utilizada em aprendizado de máquina é transformar os dados de forma que os elementos de cada dado tenham média zero e desvio padrão igual a 1.

Da mesma forma que no exemplo anterior, tem-se $m$ dados, sendo que cada um consiste de um vetor linha de dimensão $n$. 

Nesse caso a matriz de dados, V, é representada de forma mais conveniente de acordo com a equação (3.5). 

$$V = \begin{pmatrix}v_1 ... v_n\end{pmatrix}_{(m,n)}$$   	

onde $v_j$ é a $j$-ésima coluna da matriz $V$, ou seja, é um vetor coluna de $m$ elementos. Observe que nesse caso a normalização é realizada ao longo das colunas. 

Deseja-se que cada elemento das colunas da matrix $V$ tenha média igual a zero $\to$ assim, a média e o desvio padrão deve ser calculada para cada coluna da matriz $V$ e a normalização é realizada para cada coluna. 

A normalização das colunas da matriz nesse exemplo é feita subtraindo de cada elemento a média da coluna e dividindo pelo seu desvio padrão:

$$v_{j,nomr} = \frac{v_j - \overline{v}_j}{\sigma_j}, para  j = 1,...,n$$

onde $\overline{v}_j$ e $\sigma_j$ são respectivamente o valor médio e o desvio padrão da $j$-ésima coluna da matriz $V$.

No código abaixo é criada e executada uma função que realiza essa normalização.

In [34]:
# Função com cálculo vetorizado para normalizar colunas de uma matriz
def norm_col(V):
    """
    Argumento: V = matriz numpy de dimensões (m, n)
    Retorna: 
    Vnorm = matriz normalizada por coluna
    media_col = valor médio das colunas da matriz original
    std_col = desvio padrão das colunas da matriz original
    """
    
    # Calculo da média de cada coluna da matriz A
    media_col = np.mean(V, axis = 1)
    
    # Determina valor absoluto máximo de cada coluna
    std_col = np.std(V, axis=1)
    
    # Normalização das colunas na matriz
    Vnorm = (V - media_col)/std_col
    
    return Vnorm, media_col, std_col

# Define matriz V e executa função norm_col
V = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
Vnorm, media_col, std_col = norm_col(V)

print('Matriz V =', V)
print('Média das colunas =', media_col)
print('Desvio padrão das colunas =', std_col)
print('Matriz com colunas normalizadas =', Vnorm)

Matriz V = [[1 2 3]
 [2 3 4]
 [3 4 5]]
Média das colunas = [2. 3. 4.]
Desvio padrão das colunas = [0.81649658 0.81649658 0.81649658]
Matriz com colunas normalizadas = [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 7. Propagação para frente em uma camada

As equações da propagação para frente na $l$-ésima camada de uma RNA são definidas por:

$$z^{[l]} = W^{[l]} a^{[l-1]} + b^{[l]}$$

$$a^{[l]} = \sigma(z^{[l]})$$
 
onde:

- dimensão de $W^{[l]} =  (n^{[l]}, n^{[l-1]})$;
- dimensão de $a^{[l-1]}  = (n^{[l-1]}, 1)$;
- dimensão de $b^{[l]}$ = dimensão de $a^{[l]}$ = dimensão de $z^{[l]} = (n^{[l]}, 1)$.

Para inicializar os pesos das ligações de uma RNA são usados números aleatórios $\to$ a biblioteca Numpy possui a função `random.random()` para gerar números aleatórios com distribuição uniforme entre 0 e 1.

No código abaico apresenta um exemplo do cálculo vetorizado da propagação para frente de uma camada de uma RNA.


In [36]:
# Importa bilblioteca numpy
import numpy as np

# Função para cálculo da propagação para frente na camada l
def frente(W, b, a_ant):
    z = np.dot(W,a_ant) + b
    a = 1/(1 + np.exp(-z))
    return a

# Inicialização dos parâmetros da camada da RNA
W = np.random.random((4,3))
b = np.random.random((4,1))
a_ant = np.ones((3,1))

# Calculo da propagação para frente na camada
a = frente(W,b,a_ant)

# Apresenta resultados
print("W = ",W)
print("b = ",b)
print("a_ant = ",a_ant)
print("a = ",a)

W =  [[0.18236187 0.23712558 0.79159864]
 [0.63347229 0.38816348 0.87673339]
 [0.09491629 0.06247212 0.1737442 ]
 [0.626605   0.99089785 0.70030163]]
b =  [[0.87770138]
 [0.25466509]
 [0.02661593]
 [0.68330255]]
a_ant =  [[1.]
 [1.]
 [1.]]
a =  [[0.88980859]
 [0.89595198]
 [0.58849531]
 [0.95262411]]


- Observa-se que essa camada possui 4 neurônios e a camada anterior possui 3 neurônios, ou seja: $n^{[l]} = 4$ e $n^{[l-1]} = 3$.


- A função `np.random.random()` recebe uma tuple que repesenta os números de elementos de cada eixo do tensor gerado.